### ISSUE TITLE
searchlight: Add example with multiple return values

### ISSUE THREAD

**Issue by mihaic** [IntelPNI/brainiak#267]
It is not trivial to deal with the output array containing tuples (see issue #265); an example would help.

**Comment by hcchang73** [comment]
Ur...Now I am having problem saving the results, since the outputs is a 3D array in which some element is arrays with 3 values and some are just an NaN.
Error message as below: 

>>> outputs.tofile(textType+'_perm' +str(iteration)+ '_rad'+str(rad)+'_outputs.dat')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: cannot write object arrays to a file in binary mode
>>> np.array(outputs,dtype=float)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: setting an array element with a sequence.
>>> scipy.io.savemat(textType+'_perm' +str(iteration)+ '_rad'+str(rad)+'_sim.mat', {'data':outputs})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/people/huichuan/.local/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 211, in savemat
    MW.put_variables(mdict)
  File "/usr/people/huichuan/.local/lib/python3.6/site-packages/scipy/io/matlab/mio5.py", line 846, in put_variables
    self._matrix_writer.write_top(var, asbytes(name), is_global)
  File "/usr/people/huichuan/.local/lib/python3.6/site-packages/scipy/io/matlab/mio5.py", line 587, in write_top
    self.write(arr)
  File "/usr/people/huichuan/.local/lib/python3.6/site-packages/scipy/io/matlab/mio5.py", line 618, in write
    self.write_cells(narr)
  File "/usr/people/huichuan/.local/lib/python3.6/site-packages/scipy/io/matlab/mio5.py", line 723, in write_cells
    self.write(el)
  File "/usr/people/huichuan/.local/lib/python3.6/site-packages/scipy/io/matlab/mio5.py", line 608, in write
    % (arr, type(arr)))
TypeError: Could not convert None (type <class 'NoneType'>) to array

**Comment by mihaic** [comment]
@mjanderson09, can you please look into this?

**Comment by hcchang73** [comment]
I saved the data as a matlab mat file by the following scripts.
But it's not the most elegant way to do it: 

_np.save('simMat_segment_rad'+str(rad),outputs)

outputs2=np.reshape(outputs,61*73*61)
del outputs
outputs3=np.empty((0,45,45))
keptvox=np.empty((0))

for i in range(0,outputs2.shape[0]):
    if outputs2[[i]]!=None and np.nansum(np.hstack(outputs2[[i]].flat))!=0:
            output_temp=np.expand_dims(outputs2[i].astype(float), axis=0)
            outputs3=np.append(outputs3,output_temp,axis=0)
            keptvox= np.append(keptvox,np.array(i+1).reshape(1)) # python index starts from 0, unlike matlab, which starts from 1
    print(i)

scipy.io.savemat('simMat_segment_rad'+str(rad)+'.mat', dict(data=outputs3, keptvox=keptvox))_
