### ISSUE TITLE
Fix installation from PyPI

### ISSUE THREAD

**Issue by mihaic** [IntelPNI/brainiak#61]
There is a difference in the behavior of `pip install` based on the package specification. When installing form Git, it installs the dependencies before building the wheel. When installing from PyPI, it first tries to build the wheel, and only then it installs the dependencies. Here are relevant excerpts:

`pip3 install -v git+https://github.com/IntelPNI/brainiak@v0.1`
```
  Using cached pybind11-1.8.1-py2.py3-none-any.whl
  Downloading from URL https://pypi.python.org/packages/e8/bb/cb21c4b8da28d94df193bd83fe399e13dd38b7eba6fed52546d4fb1c2908/pybind11-1.8.1-py2.py3-none-any.whl#md5=468347b8f3c1114c6cb23df6b4186bbb (from https://pypi.python.org/simple/pybind11/)
Installing collected packages: pybind11, brainiak

  Running setup.py install for brainiak ...
```

`pip install -v brainiak`
```
  Using cached pybind11-1.8.1-py2.py3-none-any.whl
  Downloading from URL https://pypi.python.org/packages/e8/bb/cb21c4b8da28d94df193bd83fe399e13dd38b7eba6fed52546d4fb1c2908/pybind11-1.8.1-py2.py3-none-any.whl#md5=468347b8f3c1114c6cb23df6b4186bbb (from https://pypi.python.org/simple/pybind11/)
Building wheels for collected packages: brainiak
  Running setup.py bdist_wheel for brainiak ...

[verbose output showing it fails because pybind11 is not installed]

Failed to build brainiak
Installing collected packages: pybind11, brainiak

  Running setup.py install for brainiak ...
```

**Comment by mihaic** [comment]
Pip support for [PEP 518 -- Specifying Minimum Build System Requirements for Python Projects](https://www.python.org/dev/peps/pep-0518/) would fix our problem.
https://github.com/pypa/pip/issues/3691

**Comment by mihaic** [comment]
I am re-tagging this as "enhancement" because it does not really break anything. It only scares the users who might think something is wrong. The installation continues fine, even if the wheel is not built.

**Comment by mihaic** [comment]
Another argument to leave this be and wait for PEP 518 to be implemented: The latest version of SciPy has the same problem.
```
$ pip3 install scipy-0.18.0rc2.tar.gz 
Processing ./scipy-0.18.0rc2.tar.gz
Collecting numpy>=1.7.1 (from scipy==0.18.0rc2)
  Using cached numpy-1.11.1-cp34-cp34m-manylinux1_x86_64.whl
Building wheels for collected packages: scipy
  Running setup.py bdist_wheel for scipy ... error
  Complete output from command /home/mihai/.tmp/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-qmy92i29-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpz0exbw4ipip-wheel- --python-tag cp34:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-qmy92i29-build/setup.py", line 415, in <module>
      setup_package()
    File "/tmp/pip-qmy92i29-build/setup.py", line 395, in setup_package
      from numpy.distutils.core import setup
  ImportError: No module named 'numpy'
  
  ----------------------------------------
  Failed building wheel for scipy
```
